Outdoor Air Quality in the United States
========================================

## Background

Outdoor air pollution in the United States monitored and regulated by
the [Environmental Protection Agency](http://www.epa.gov) as well as
many state and local environmental agencies. Since the introduction of
the Clean Air Act in 1970, a major goal has been to reduce the levels
of outdoor air pollution so that we can maintain an adequate margin of
safety with respect to protecting public health.

So how are we doing? This is a question that can be asked and answered
in a variety of ways and different stakeholders (i.e. policy-makers,
scientists, state and local regulators) may have different levels of
interest in specific questions.


```{r,echo=FALSE}
pollutantList <- c("PM10", "PM2.5", "O3", "NO2", "SO2")
pollnames <- c("coarse particulate matter", "fine particulate matter", "ozone", "nitrogen dioxide", "sulphur dioxide")
idx <- sample(length(pollutantList), 2, replace = FALSE)
poll1 <- pollutantList[idx[1]]
poll2 <- pollutantList[idx[2]]
name1 <- pollnames[idx[1]]
name2 <- pollnames[idx[2]]
```

The goal of this project is to take the EPA's comprehensive database
of air pollution monitoring information and to tell a coherent story
about how outdoor air pollution has changed over time and space in the
United States. In this project you will examine a pair of "criteria
pollutants", which are air pollutants for which national ambient air
quality standards have been developed. 

The two pollutants that you will focus on in this project are `r poll1` (`r name1`) and `r poll2` (`r name2`).


### Data

Data for outdoor air pollution monitoring is collected by the
Environmental Protection Agency and is made available through the
EPA's [Air Quality
System](http://www.epa.gov/ttn/airs/airsaqs/detaildata/downloadaqsdata.htm)
(AQS). We have mirrored the EPA's web site on Coursera so please DO
NOT download the data from the EPA site. You can download the data
from the Coursera site directly at [URL].

## Questions to Answer

The goal of national ambient air quality standards is to set maximum
levels at which the pollutants can be found in the air. However, in
many locations in the U.S. air pollution levels exceed the standards
and thus those locations are in "non-attainment".

For this project, you need to develop a data product that answers the
following questions

* Given that various air quality control measures have been
  implemented across the country, can we observe whether air pollution
  levels have decreased over time?

* In which counties are air pollution levels decreasing the fastest?
  In which counties are they decreasing the slowest?

* Which counties and states are in attainment of the air quality
  standards which are in non-attainment?



## Milestones

1. Write a set of R functions that scrapes the necessary pollution
data from the web and arranges the dataset in appropriate directories

2. 

3. 

4. 


## What You Submit



## Grading




## Other Information
